#!/bin/sh

# run ghci with the right command line flags to launch lambdabot
ghci -Wall -Werror -fglasgow-exts -I. -pgmF ./BotPP -F -fno-warn-incomplete-patterns -fno-warn-missing-methods -fno-warn-orphans -DGHCi $*
