#! /usr/bin/env python
import sys
import time
import subprocess

def check_quit():
   for line in open('lambdabot.log', 'r'):
      if line.strip() == '[NOTICE] : Quitting':
          return True
   return False

while True:
   start = time.time()
   subprocess.call(['./run.sh'])
   stop = time.time()
   print "%s --> %fs" % (time.ctime(), stop - start)
   if check_quit() and stop - start < 300:
      sys.exit(1)
   if stop - start < 120:
      time.sleep(120 + start - stop)
