{-# LANGUAGE PatternGuards #-}
{-# LANGUAGE ScopedTypeVariables #-}

-- | URL Utility Functions

module Lambdabot.Util.Browser
    ( fetchTitle
    , fetchPage
    , fetchRaw
    , urlEncode
    ) where

import Codec.Binary.UTF8.String
import Control.Applicative
import Control.Exception (catch)
import Control.Monad.Trans
import Lambdabot.Config
import Lambdabot.Config.Reference
import Lambdabot.Monad
import Lambdabot.Util (io, limitStr)
import qualified Network.HTTP.Client          as HTTP
import qualified Network.HTTP.Client.Internal as HTTP
import qualified Network.HTTP.Client.TLS      as HTTP
import qualified Network.HTTP.Types           as HTTP
import qualified Data.ByteString.Lazy.UTF8    as U
import qualified Data.ByteString.Lazy         as L
import Network.URI
import Text.HTML.TagSoup
import Text.HTML.TagSoup.Match
import Data.Char (toLower)
import Data.List (isPrefixOf)

urlEncode :: String -> String
urlEncode = escapeURIString isUnescapedInURI

fetchAux :: MonadLB m => (HTTP.Request -> HTTP.Manager -> IO a) -> String -> m (Maybe a)
fetchAux http uri_ | Just uri <- parseURI uri_ = do
    proxy' <- getConfig proxy
    liftIO $ do
        httpman <- HTTP.newManager $
            HTTP.managerSetProxy proxy' $
            HTTP.tlsManagerSettings{
                HTTP.managerIdleConnectionCount = 0
            }
        let request = (HTTP.requestFromURI_ uri){
                    HTTP.redirectCount = 5,
                    HTTP.responseTimeout = HTTP.responseTimeoutMicro (5 * 10^6)
                }
        Just <$> http request httpman
      `catch`
        \(_ :: HTTP.HttpException) -> pure Nothing
fetchAux _ _ = return Nothing

httpRawLbs :: HTTP.Request -> HTTP.Manager -> IO (HTTP.Response String)
httpRawLbs req man = do
    res <- HTTP.httpRaw req man
    bss <- HTTP.brConsume $ HTTP.responseBody res
    return res{ HTTP.responseBody = U.toString (L.fromChunks bss) }

fetchRaw :: MonadLB m => String -> m (Maybe (HTTP.Response String))
fetchRaw = fetchAux httpRawLbs

fetchPage :: MonadLB m => String -> m (Maybe String)
fetchPage uri = do
    res <- fetchAux HTTP.httpLbs uri
    case HTTP.statusIsSuccessful . HTTP.responseStatus <$> res of
        Just True -> return $ U.toString . HTTP.responseBody <$> res
        _ -> return Nothing

-- | Fetches a page title suitable for display.  Ideally, other
-- plugins should make use of this function if the result is to be
-- displayed in an IRC channel because it ensures that a consistent
-- look is used (and also lets the URL plugin effectively ignore
-- contextual URLs that might be generated by another instance of
-- lambdabot; the URL plugin matches on 'urlTitlePrompt').
fetchTitle :: MonadLB m => String -> m (Maybe String)
fetchTitle = fmap (>>= fmap (limitStr maxTitleLength) . extractTitle) . fetchPage

-- | Limit the maximum title length to prevent jokers from spamming
-- the channel with specially crafted HTML pages.
maxTitleLength :: Int
maxTitleLength = 80

-- | Given a server response (list of Strings), return the text in
-- between the title HTML element, only if it is text/html content.
-- Now supports all(?) HTML entities thanks to TagSoup.
extractTitle :: String -> Maybe String
extractTitle = content . tags . decodeString where
    tags = closing . opening . canonicalizeTags . parseTags
    opening = dropWhile (not . tagOpenLit "title" (const True))
    closing = takeWhile (not . tagCloseLit "title")

    content = maybeText . format . innerText
    format = unwords . words
    maybeText [] = Nothing
    maybeText t  = Just (encodeString t)
