#!/usr/bin/perl
#
# author : Don Stewart
# Tue Oct  5 12:24:58 EST 2004

#
# TODO: use MiniHTTP

$page ='http://www.timeanddate.com/worldclock/results.html';

$city = $ARGV[0];

@results = `w3m -dump "$page?query=$city"`;

for (@results) {
        next if not /Current time/;
        s/^.*time\s*//;
        print;
        exit 0;
}
